spring:
  datasource:
    url: ${APPSETTING_URL}
    #username: azure
    #password: ${AZURE_DB_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect : org.hibernate.dialect.SQLServer2012Dialect