spring:
  datasource:
    url: jdbc:sqlserver://azure-database-test.database.windows.net:1433;database=azure-test;user=azure@azure-database-test;password=root123.;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    #username: azure
    #password: ${AZURE_DB_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect : org.hibernate.dialect.SQLServer2012Dialect

  #azure:
   # keyvault:
    #  enabled: true
     # uri: ${AZURE_KEYVAULT_URI}